/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_fudan_blepulse_ndk_JniUtil */

#ifndef _Included_cn_edu_fudan_blepulse_ndk_JniUtil
#define _Included_cn_edu_fudan_blepulse_ndk_JniUtil

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_fudan_blepulse_ndk_JniUtil
 * Method:    logCalc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_edu_fudan_blepulse_ndk_JniUtil_logCalc
  (JNIEnv *, jclass, jstring);

JNIEXPORT jdouble JNICALL
Java_cn_edu_fudan_blepulse_ndk_JniUtil_calcArea(JNIEnv *env, jclass type, jintArray data_);

#ifdef __cplusplus
}
#endif
#endif
